Implement postgresql package
openinfradev/tks-contract pull request #3
Opened 2021-05-20 01:08 UTC by jabbukka

* lib/pq와 database/sql을 사용하는 postgresql package 구현
* 주요 기능
  * Insert / Update / Delete / Get
  * Transaction Begin / Commit
  * 그 외 기능은 필요시 추가 구현 

* go-sqlmock library 를 사용한 unittest code 작성

2021-05-20 11:27 UTC, zugwan approved these changes
LGTM

2021-05-21 01:09 UTC, robertchoi80 commented on pkg/postgresql/accessor.go
> +	rows, err := tx.Query(query)
value 가 빠져있습니다

2021-05-21 02:12 UTC, jabbukka commented on pkg/postgresql/accessor.go
> +	rows, err := tx.Query(query)
수정하였습니다.

2021-05-21 02:40 UTC, robertchoi80 commented on pkg/postgresql/accessor.go
> +	args := getValueSliceFromMaps(conditions)
변수명을 좀 통일하면 더 좋을 것 같습니다.  지금 함수마다, args, conditionValues 등 다른 이름으로 사용되고 있어서 통일하면 가독성이 좋아질거 같아요.  저 개인적으로는 Delete()에 사용하신 방식이 제일 명확한 거 같습니다.

2021-05-21 02:41 UTC, robertchoi80 requested changes
추가 의견 남겼습니다

2021-05-21 02:48 UTC, jabbukka commented on pkg/postgresql/accessor.go
> +	args := getValueSliceFromMaps(conditions)
네 conditionValues, conditionKeySql로 통일 시켰습니다~

2021-05-21 04:47 UTC, robertchoi80 approved these changes

2021-05-21 04:47 UTC, merged